### PR TITLE
Updated version

### PR DESCRIPTION
**Pull request by aserafin**
@sauloperez do you need anything else to update version and create release on github? In case yes, please let me know and will be happy to help :)

### CODE REVIEW

**Comment by sauloperez** [comment]
Wow, thanks @aserafin ! I think that's all. I'll release it in the afternoon. I have to remind myself how not to mess with the various branches/gem versions :trollface:

**Review by franciscoj — APPROVED** [review]

**Review by sauloperez — APPROVED** [review]

**Comment by sauloperez** [comment]
I commited your changes myself into the v4.0 branch. You can upgrade your gem already https://rubygems.org/gems/percona_migrator/versions/1.1.0

**Comment by aserafin** [comment]
@sauloperez we are actually using master with rails 4.2 support - and 1.1.0 version you pushed to rubygems does not have that right?

**Comment by sauloperez** [comment]
Nope, then we'll have to release a new one bumping up the major version.

**Comment by aserafin** [comment]
@sauloperez gotcha - are you planning to do it or you're gonna wait till the renaming gem to departure will be ready?

**Comment by sauloperez** [comment]
No, I don't want you to wait. It already has the deprecation warnings, so it's fine until we have Departure ready in one or two weeks. I'm pushing the tags and to rubygems. I'll figure out the best branching model and release process as well.

**Comment by sauloperez** [comment]
Done! https://rubygems.org/gems/percona_migrator/versions/3.0.0 that should work. I leave the 2.0.0 series for Rails 4.1 which is not yet released.

Thanks a lot for your help @aserafin !

**Comment by aserafin** [comment]
Awesome - thank you very much 🎉

**Pull request closed without merging**
