### PR TITLE
Manage cases where the port is not the default one for the host, wrap…

### PR DESCRIPTION
**Pull request by Nakort**
… password in quotes for special character handling.

### CODE REVIEW

**Comment by andresgutgon** [comment]
👍

**Review by franciscoj — COMMENTED** [review]
A million of thanks for this contribution!

I have a small comment let me know what you think...

Instead of adding complexity into `to_s` we could have the `port` method returning the default already. Like this:

```ruby
DEFAULT_PORT = 3306

def port
  ENV.fetch('PERCONA_DB_PORT', connection_data[:port] || DEFAULT_PORT)
end
```

That way the `to_s` method would be super simple, since we can always just add the `-P`

```ruby
def to_s
  @to_s ||= "-h #{host} -P #{port} -u #{user} #{password_artument}"
end
```

What do you think?

*EDIT*:

Also I think that for now we don't need to get the port from the devenv. That's what the configuration block is for.

```ruby
Departure.configure do |config|
  config.port = ENV['PERCONA_DB_PORT']
end
```

So the `port` method could be:

```ruby
def port
  connection_data[:port] || DEFAULT_PORT
end
```

**Comment by sauloperez** [comment]
Agree with @franciscoj . Regarding the env var, you can also do something like the following in your app's `config/database.yml`:

```ruby
common: &common
  adapter: <%= ENV.fetch('DB_ADAPTER', 'mysql2') %>
  host: <%= ENV.fetch('DB_HOST', 'localhost') %>
  port: <%= ENV.fetch('DB_PORT', 3306) %>
  username: <%= ENV.fetch('DB_USERNAME', 'root') %>
  password: <%= ENV['DB_PASSWORD'] %>
  encoding: utf8
  local_infile: true
  strict: false

development: &development
  <<: *common
  database: <%= ENV.fetch('DB_NAME', 'redbooth_development') %>

(...)
```

This way you have one place to change this setting for your app.

**Comment by Nakort** [comment]
@sauloperez @franciscoj agree with both comments,  I have updated my PR.

**Review by franciscoj — APPROVED** [review]

**Comment by sauloperez** [comment]
resolves #67

**Comment by sauloperez** [comment]
thanks a lot @Nakort !

**Pull request merged**
