### PR TITLE
Global percona args

### PR DESCRIPTION
**Pull request by aserafin**
This pull request solves issue #50 - it adds `global_percona_args` configuration option that allows to specify some arguments that will be used every time when sql command is executed via `pt-online-schema-change`. Values provided there can be change by `PERCONA_ARGS` env variable.

### CODE REVIEW

**Review by sauloperez — APPROVED** [review]
Looks good

**Comment by aserafin** [comment]
@sauloperez when do you think you will be able to merge this? :)

**Review by franciscoj — APPROVED** [review]
Looks good!

**Comment by sauloperez** [comment]
It resolves #50

**Comment by sauloperez** [comment]
weird... my comment above should have closed the issue as well 🤔

**Pull request merged**
